version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - wp_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
   depends_on:
     - db
   image: wordpress:latest
   volumes:
     - ./themes:/var/www/html/wp-content/themes/
     - ./plugins:/var/www/html/wp-content/plugins/
   ports:
     - "8000:80"
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
volumes:
    wp_db_data: {}
